output "iam_console_login_url" {
  description = "The URL for the IAM user to log into the AWS console."
  value       = "https://${data.aws_caller_identity.current.account_id}.signin.aws.amazon.com/console"
}

output "initial_password" {
  description = "The autogenerated password for the IAM user (only use for first login)."
  value       = aws_iam_user_login_profile.iam_user_login_profile.password
  sensitive   = true
}

output "ec2_public_ip" {
  description = "The public IP of the management server"
  value       = aws_instance.management_server.public_ip
}

output "ec2_ssh_command" {
  description = "Command to SSH into the EC2 instance"
  value       = "ssh -i ${var.key_pair_name}.pem ec2-user@${aws_instance.management_server.public_ip}"
}